apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-users
  namespace: prod
spec:
  selector:
    matchLabels:
      app: ms-users
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: ms-users
    spec:
      containers:
        - name: ms-users
          volumeMounts:
            - mountPath: "/usr/src/app/keys"
              name: jwt-rsa-keys
              readOnly: true
          image: sacha2dev/breizhsport-user-service:dev
          env:
            - name: PORT
              value: "3001"
            - name: DB_HOST
              value: db-users
            - name: DB_DIALECT
              value: "mysql"
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  key: db-name
                  name: ms-users
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: ms-users
                  key: db-user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ms-users
                  key: db-password
            - name: FIRST_USER_EMAIL
              valueFrom:
                secretKeyRef:
                  name: ms-users
                  key: first-user-email
            - name: FIRST_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: first-user-password
                  name: ms-users
          ports:
            - containerPort: 3001
          resources:
            requests:
              cpu: 50m
              memory: 150Mi
            limits:
              cpu: 100m
              memory: 200Mi
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 3001
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 3001
            initialDelaySeconds: 15
      volumes:
        - name: jwt-rsa-keys
          secret:
            secretName: jwt-rsa-keys
