apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-end
  namespace: prod
spec:
  selector:
    matchLabels:
      app: front-end
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: front-end
    spec:
      containers:
        - name: front-end
          image: keke65/breizhsport-front:v0.0.5
          env:
            - name: PUBLIC_MS_USER
              valueFrom:
                configMapKeyRef:
                  name: front-end
                  key: ms-users
            - name: PUBLIC_MS_PRODUCT
              valueFrom:
                configMapKeyRef:
                  name: front-end
                  key: ms-products
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 150m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 250Mi
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 15
