name: Create Azure Kubernetes Service
on:
  workflow_call:
    secrets:
      AZURE_CLIENT_ID:
        required: true
        description: ""
      AZURE_TENANT_ID:
        required: true
        description: ""
      AZURE_SUBSCRIPTION_ID:
        required: true
        description: ""
    inputs:
      resource_group_name:
        required: true
        type: string
      aks_resource_group_name:
        required: true
        type: string
      aks_name:
        required: true
        type: string

permissions:
  id-token: write
  contents: read
jobs:
  create_aks:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Create AKS
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az aks create --resource-group ${{inputs.resource_group_name}} \
            --name ${{inputs.aks_name}} --location francecentral \
            --node-count 1 --node-vm-size "Standard_B2s" \
            --load-balancer-sku basic --node-osdisk-type ephemeral \
            --node-osdisk-size 30 --generate-ssh-keys \
            --node-resource-group ${{inputs.aks_resource_group_name}} \
