name: Delete Azure resource group
on:
    workflow_call:
        secrets:
            AZURE_CLIENT_ID:
                required: true
                description: ''
            AZURE_TENANT_ID:
                required: true
                description: ''
            AZURE_SUBSCRIPTION_ID:
                required: true
                description: ''
        inputs:
            resource_group_name:
                required: true
                type: string

permissions:
    id-token: write
    contents: read
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        environment: prod
        steps:
            - name: Azure login
              uses: azure/login@v2
              with:
                  client-id: ${{ secrets.AZURE_CLIENT_ID }}
                  tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                  subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

            - name: Delete resource group
              uses: azure/cli@v2
              with:
                  azcliversion: latest
                  inlineScript: |
                      az group delete --name ${{inputs.resource_group_name}} --force-deletion-types Microsoft.Compute/virtualMachineScaleSets -y
