name: Remove tag on docker hub

on:
    workflow_call:
        secrets:
            DOCKER_PAT:
                required: true
            DOCKER_USERNAME:
                required: true
        inputs:
            old-image:
                type: string
                required: true
            new-image:
                type: string
                required: true
jobs:
    login_and_delete:
        runs-on: ubuntu-latest
        steps:
            - name: Login to Docker Hub
              uses: docker/login-action@v3.3.0
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PAT }}
            - name: Pull old image
              run: |
                  docker image pull ${{inputs.old-image}}
            - name: Rename ${{inputs.old-image}} into ${{inputs.new-image}}
              run: |
                  docker tag ${{inputs.old-image}} ${{inputs.new-image}}
            - name: Push ${{inputs.new-image}}
              run: |
                  docker push ${{inputs.new-image}}
