name: Modify image version

on:
  workflow_call:
    inputs:
      yaml_path:
        type: string
        required: true
      new_image_version:
        type: string
        required: true
      commit_message:
        type: string
        required: true
    secrets:
      TOKEN_GITHUB:
        required: true
      DOCKER_IMAGE:
        required: true

jobs:
  modify_image_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: Breizhsport-cesi-pau/breizhsport-infra/
          path: other-repo
          token: ${{ secrets.TOKEN_GIT }}
      - name: Update values and commit
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: ${{inputs.yaml_path}}
          propertyPath: "spec.template.spec.containers[0].image"
          value: "${{secrets.DOCKER_IMAGE}}:${{inputs.new_image_version}}"
          commitChange: true
          branch: main
          repository: Breizhsport-cesi-pau/breizhsport-infra
          message: ${{inputs.commit_message}}
          token: ${{secrets.TOKEN_GITHUB}}
          workDir: other-repo
