name: Publish to docker hub

on:
  workflow_call:
    secrets:
      DOCKER_USERNAME:
        required: true
        description: ""
      DOCKER_PAT:
        required: true
        description: ""
      tags:
        required: true
        description: ""

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PAT }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.7.1
      - name: Build and push
        uses: docker/build-push-action@v6.10.0
        with:
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max`
          file: ./Dockerfile
          push: true
          tags: ${{secrets.tags}}
