name: Performance tests

on:
  workflow_call:
    inputs:
      url:
        type: string
        required: true
jobs:
  spike_and_load-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: grafana/setup-k6-action@v1
      - name: Run spike test
        run: |
          k6 run -e URL=${{inputs.url}} --out json=requests.spike.json --compatibility-mode=experimental_enhanced ./tests/performance/spike.ts
      - name: Run load test
        run: |
          k6 run -e URL=${{inputs.url}} --out json=requests.load.json --compatibility-mode=experimental_enhanced ./tests/performance/load.ts
      - name: Upload requests results artifacts
        uses: actions/upload-artifact@v4
        with:
          name: performance-tests-results
          path: ./requests.*.json
          retention-days: 3
          include-hidden-files: true
